### ISSUE TITLE
Not prompting for aws role-arn when passing eks region option alone

### ISSUE THREAD

**Issue by gseshagirirao** [fidelity/kconnect#108]
While trying to login using kconnect with options  -- use eks --region flag, it is not prompting for the aws role-arn choices.

command : kconnect use eks --region us-east-1 

The command prompted for the username, password then it should give options for aws-role/accounts.

Steps to reproduce:

kconnect use eks --region us-east-1
INFO[0000] kconnect - the kubernetes cli (0.1.1)        
INFO using cluster provider eks                    command=use
INFO using identity provider saml                  command=use
INFO authenticating user                           command=use provider=saml
? Enter your username XXXX
INFO using cached creds                            command=use provider=saml
INFO discovering clusters using eks provider       command=use
INFO discovering EKS clusters AWS                  command=use provider=eks
ShINFO setting current context to: kconnect-kconnect-saml-eks-XXXXX@kconnect-eks-XXXX package=kubeconfig
INFO kubeconfig updated: /Users/XXXXXX/.kube/config  package=kubeconfig

The workaround as of now is to use the --force command to prompt for account choices.

**Environment:**

- kconnect version (use `kconnect version`): 0.1.1
- Kubernetes version (use `kubectl version`):  v1.19.2
- OS (e.g. from `/etc/os-release`): Mac
- Target environment (e.g. EKS, AKS, Rancher): EKS
- Authentication Used (e.g. SAML, IAM, Azure AD):   SAML

**Comment by richardcase** [comment]
This is related to the aws profile name. We should probably create unique profile names by default for each cluster/user combination.

We should still allow a user to specify an explicit aws profile and perhaps warn the user? We shoudl also add this to a troubleshooting section.

**Comment by seankelly001** [comment]
Hi @richardcase , I believe this is because kconnect is checking if the aws credentials are expired, and if not then it won't prompt for new credentials. This also happens when reconnecting to the same region before credentials have expired. I think that even if credentials aren't expired, kconnect should renew the token, and prompt for role selection every time kconnect is run. Say for example a user wanted to connect to the same cluster with a different IAM role (eks), at the moment this would be quite difficult to do. Thoughts?
