### ISSUE TITLE
kubeconfig context is not changing after kconnect to command

### ISSUE THREAD

**Issue by gseshagirirao** [fidelity/kconnect#109]
After setting up the alias for different clusters and trying to use the kconnect to <alias> name, the KUBECONFIG has not updated , as a result the correct cluster is not connected after successful command execution.

The KUBECONFIG context should have updated with current alias name.

Steps to reproduce:

kconnect-kconnect-saml-eks-XX-YY-us-east-1@kconnect-eks-XX-YY-us-east-1:default) XXXXXXXX@MACLB193610   kconnect to AAA-us-east-2

INFO[0000] kconnect - the kubernetes cli (0.1.1)        
INFO[0000] authenticating user                           command=to provider=saml
INFO[0000] cached creds expired or force enabled, renewing  command=to provider=saml
INFO selected role: arn:aws:iam::ZZZZZ:role/ZZZZZ 
INFO Requesting AWS credentials using SAML        
INFO[0004] getting cluster arn:aws:eks:us-east-2:ZZZZ:cluster/AAA-AAA-us-east-2 using eks provider  command=to
INFO[0004] getting EKS cluster with id: arn:aws:eks:us-east-2:XXXXXX:cluster/AAA-AAA-us-east-2  command=to provider=eks
INFO kubeconfig updated:                           package=kubeconfig
(⎈ |kconnect-kconnect-saml-eks-XXX-XXX-us-east-1@kconnect-eks-XXX-XX-us-east-1:default

the last list should have been (expected result:)
(⎈ |kconnect-kconnect-saml-eks-AAA-AAA-us-east-1@kconnect-eks-AAA-AAA-us-east-1:default

**Comment by richardcase** [comment]
Thanks @gseshagirirao . That should set the current context by default....i'll investigate.

**Comment by seankelly001** [comment]
Hi @richardcase , I believe this is because kconnect is checking if the aws credentials are expired, and if not then it won't prompt for new credentials. This also happens when reconnecting to the same region before credentials have expired. I think that even if credentials aren't expired, kconnect should renew the token, and prompt for role selection every time kconnect is run. Say for example a user wanted to connect to the same cluster with a different IAM role (eks), at the moment this would be quite difficult to do. Thoughts?

**Comment by richardcase** [comment]
@seankelly001 - if we use a unique profile name for provider/region/role would that be enough so that we can then use the cache credentials? Or as you say is it easier if we just never use cached credentials and ask for the username/password every time?

**Comment by seankelly001** [comment]
HI Richard, I actually commented on the wrong issue, apologies.. I was referring to issue #108
